project:
  type: website
  output-dir: docs/

format: 
  revealjs:
    theme: simple
    logo: "Images/MQ_INT_HOR_RGB_POS.jpg"
    footer: "&copy; 2024, License: CC-BY &bull; https://github.com/Denubis/germany-keynote-ai-policy-briefing"

  
  beamer: 
    aspectratio: 169


    